import "./globals.css";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

const borel = Josefin_Sans({ subsets: ["latin"], weight: ["600"] });

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang="en">
   <body className={borel.className}>
    <Header />
    {children}
    <Footer />
   </body>
  </html>
 );
}
